language: go
sudo: required
dist: trusty

go:
 - 1.9.2

addons:
   apt:
     packages:
       - libnetfilter-queue-dev
       - libnetfilter-log-dev
       - iptables
       - ipset

env:
  global:
    - TOOLS_CMD=golang.org/x/tools/cmd
    - PATH=$GOROOT/bin:$PATH
    - SUDO_PERMITTED=1

before_install:
  - go get -u gopkg.in/alecthomas/gometalinter.v1
  - go get -u github.com/golang/dep/cmd/dep
  - gometalinter.v1 --install
  - mkdir -p ${GOPATH}/src/go.aporeto.io && ln -s ${TRAVIS_BUILD_DIR} ${GOPATH}/src/go.aporeto.io/trireme-lib

install:
  - dep ensure -v
  - cd ${GOPATH}/src/github.com/docker/docker && rm -rf vendor/golang.org/x/net/context && cd -
  - go get -t -v ./...
  
script:
  - gometalinter.v1 --skip=mockdocker --disable-all --enable=vet --enable=vetshadow --enable=errcheck --enable=golint --enable=structcheck --enable=aligncheck --enable=deadcode --enable=ineffassign --enable=gotype --enable=goimports --enable=varcheck --enable=interfacer --enable=goconst --enable=staticcheck --enable=unused --enable=misspell --deadline=10m ./...
  - ./.test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
