language: go
sudo: required
dist: trusty

go_import_path: go.aporeto.io/trireme-lib

go:
 - 1.9.2

addons:
   apt:
     packages:
       - libnetfilter-queue-dev
       - libnetfilter-log-dev
       - iptables
       - ipset

env:
  global:
    - TOOLS_CMD=golang.org/x/tools/cmd
    - PATH=$GOROOT/bin:$PATH
    - SUDO_PERMITTED=1

before_install:
  - go get -u github.com/alecthomas/gometalinter
  - gometalinter --install
  - go get -u github.com/golang/dep/cmd/dep
  - mkdir -p ${GOPATH}/src/go.aporeto.io && ln -s ${TRAVIS_BUILD_DIR} ${GOPATH}/src/go.aporeto.io/trireme-lib

install:
  - dep ensure -v
  
script:
  - gometalinter --vendor --skip=mockdocker --disable-all --enable=vet --enable=vetshadow --enable=errcheck --enable=golint --enable=deadcode --enable=ineffassign --enable=gotype --enable=goimports --enable=interfacer --enable=goconst --enable=misspell --deadline=10m ./...
  - ./.test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
