language: go
sudo: required
dist: trusty

go_import_path: go.aporeto.io/trireme-lib

go:
 - 1.11

addons:
   apt:
     packages:
       - libnetfilter-queue-dev
       - libnetfilter-log-dev
       - iptables
       - ipset

env:
  global:
    - TOOLS_CMD=golang.org/x/tools/cmd
    - PATH=$GOROOT/bin:$PATH
    - SUDO_PERMITTED=1

before_install:
  - go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
  - go get -u github.com/golang/dep/cmd/dep

install:
  - dep ensure -v

script:
  - ./.test.sh
  - golangci-lint run --deadline=5m --disable-all --exclude-use-default=false --enable=errcheck --enable=goimports --enable=ineffassign --enable=golint --enable=unused --enable=structcheck --enable=varcheck --enable=ineffassign --enable=deadcode --enable=misspell ./...


after_success:
  - bash <(curl -s https://codecov.io/bash)
