language: go
sudo: required
dist: trusty

go:
 - 1.8.1

addons:
   apt:
     packages:
       - libnetfilter-queue-dev
       - libnetfilter-log-dev
       - iptables
       - ipset

env:
  global:
    - TOOLS_CMD=golang.org/x/tools/cmd
    - PATH=$GOROOT/bin:$PATH
    - SUDO_PERMITTED=1

before_install:
  - go get -u gopkg.in/alecthomas/gometalinter.v1
  - go get -v github.com/Masterminds/glide
  - gometalinter.v1 --install

install:
  - mkdir -p $GOPATH/src/github.com/docker && cd $GOPATH/src/github.com/docker && git clone https://github.com/docker/docker -b 1.13.x docker && cd -
  - go get -t -v ./...
  - cd $GOPATH/src/github.com/smartystreets/assertions && git checkout 1.6.0 && go install && cd -
  - cd $GOPATH/src/github.com/smartystreets/goconvey && git checkout 1.6.2 && go install && cd -


script:
  - gometalinter.v1 --disable-all --enable=vet --enable=vetshadow --enable=golint --enable=structcheck --enable=aligncheck --enable=deadcode --enable=ineffassign --enable=gotype --enable=goimports --enable=varcheck --enable=interfacer --enable=goconst --enable=gosimple --enable=staticcheck --enable=unused --enable=misspell --deadline=5m ./...
  - ./.test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
