language: go
sudo: required
dist: bionic

go_import_path: go.aporeto.io/trireme-lib

matrix:
  include:
  - go: "1.13.x"
  - go: "1.14.x"
  - go: master
  allow_failures:
  - go: master
  fast_finish: true

addons:
   apt:
     packages:
       - libnetfilter-queue-dev
       - libnetfilter-log-dev
       - iptables
       - ipset
       - wine-stable

env:
  global:
    - TOOLS_CMD=golang.org/x/tools/cmd
    - PATH=$GOROOT/bin:$PATH
    - SUDO_PERMITTED=1

before_install:
  - GO111MODULE=on go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.21.0
  - GO111MODULE=off go get github.com/golang/dep/cmd/dep
  - sudo apt-get install wine32

install:
  - dep ensure
  - ./fix_bpf
  - dep status || true

script:
  - GO111MODULE=off ./.test.sh
  - golangci-lint run --deadline=10m --disable-all --exclude-use-default=false --enable=errcheck --enable=goimports --enable=ineffassign --enable=govet --enable=golint --enable=unused --enable=structcheck --enable=varcheck --enable=deadcode --enable=unconvert --enable=goconst --enable=gosimple --enable=misspell --enable=staticcheck --enable=unparam --enable=prealloc --enable=nakedret --enable=gofmt --enable=typecheck --skip-dirs=vendor/github.com/iovisor ./...
  - GO111MODULE=off ./.lint.windows.sh
  - GO111MODULE=off ./.test.windows.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
