language: go
sudo: required
dist: trusty

go:
 - 1.7.3

addons:
   apt:
     packages:
       - libnetfilter-queue-dev
       - iptables

env:
  global:
    - TOOLS_CMD=golang.org/x/tools/cmd
    - PATH=$GOROOT/bin:$PATH
    - SUDO_PERMITTED=1

before_install:
  - go get -u gopkg.in/alecthomas/gometalinter.v1
  - gometalinter.v1 --install

script:
  - go get -v -t ./...
  - gometalinter.v1 --disable-all --enable=vet --enable=vetshadow --enable=golint --enable=structcheck --enable=aligncheck --enable=deadcode --enable=ineffassign --enable=gotype --enable=goimports --enable=varcheck --enable=interfacer --enable=goconst --enable=gosimple --enable=staticcheck --enable=unused --enable=misspell --deadline=30s
  - ./.test.sh
  - cd example
  - make build 

after_success:
  - bash <(curl -s https://codecov.io/bash)
