language: go
sudo: required
dist: trusty

go_import_path: go.aporeto.io/trireme-lib

go:
 - 1.9.2

addons:
   apt:
     packages:
       - libnetfilter-queue-dev
       - libnetfilter-log-dev
       - iptables
       - ipset

env:
  global:
    - TOOLS_CMD=golang.org/x/tools/cmd
    - PATH=$GOROOT/bin:$PATH
    - SUDO_PERMITTED=1

before_install:
  - go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
  - go get -u github.com/golang/dep/cmd/dep
  - mkdir -p ${GOPATH}/src/go.aporeto.io && ln -s ${TRAVIS_BUILD_DIR} ${GOPATH}/src/go.aporeto.io/trireme-lib
  - goimports ${GOPATH}/src/go.aporeto.io/trireme-lib/controller/internal/enforcer/nfqdatapath/datapath_test.go > ${GOPATH}/src/go.aporeto.io/trireme-lib/controller/internal/enforcer/nfqdatapath/datapath_test.go.bk
  - diff ${GOPATH}/src/go.aporeto.io/trireme-lib/controller/internal/enforcer/nfqdatapath/datapath_test.go ${GOPATH}/src/go.aporeto.io/trireme-lib/controller/internal/enforcer/nfqdatapath/datapath_test.go.bk
  - goimports ${GOPATH}/src/go.aporeto.io/trireme-lib/controller/pkg/remoteenforcer/remoteenforcer_test.go > ${GOPATH}/src/go.aporeto.io/trireme-lib/controller/pkg/remoteenforcer/remoteenforcer_test.go.bk
  - diff ${GOPATH}/src/go.aporeto.io/trireme-lib/controller/pkg/remoteenforcer/remoteenforcer_test.go ${GOPATH}/src/go.aporeto.io/trireme-lib/controller/pkg/remoteenforcer/remoteenforcer_test.go.bk

install:
  - dep ensure -v

script:
  - ./.test.sh
  - golangci-lint run \
        --deadline=5m \
        --disable-all \
        --exclude-use-default=false \
        --enable=errcheck \
        --enable=goimports \
        --enable=ineffassign \
        --enable=golint \
        --enable=unused \
        --enable=structcheck \
        --enable=varcheck \
        --enable=ineffassign \
        --enable=deadcode \
        --enable=unconvert \
        --enable=misspell \
        --enable=unparam \
        ./...


after_success:
  - bash <(curl -s https://codecov.io/bash)
