required = ["github.com/docker/distribution"]

[[constraint]]
  branch = "upgrade-sirupsen-logrus"
  name = "github.com/aporeto-inc/go-ipset"

[[constraint]]
  name = "github.com/docker/docker"
  version = "19.03"
  source = "github.com/docker/engine"

[[constraint]]
  name = "github.com/docker/distribution"
  version = "2.7.1"

[[override]]
  name = "github.com/mdlayher/netlink"
  branch = "master"

# Conntrack dependencies from forked branches
[[constraint]]
  name = "github.com/ti-mo/conntrack"
  source = "https://github.com/aporeto-inc/conntrack.git"
  revision = "309d2d6a30782ae8f0c68f2dda0774966523e469"

#
# The most significant dependency for the Kubernetes monitor: the controller-runtime
# NOTE: change with care and always adjust the Kubernetes dependencies below
#
[[override]]
  name = "sigs.k8s.io/controller-runtime"
  version = "v0.2.2"

#
# Kubernetes dependencies
# NOTE: always match exactly to what controller-runtime uses
#
[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.14.1"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.14.1"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.14.1"

[[override]]
  name = "k8s.io/apiserver"
  version = "kubernetes-1.14.1"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.14.1"

[[constraint]]
  name = "k8s.io/cri-api"
  version = "kubernetes-1.16.0"

[[override]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.14.1"

[[override]]
  name = "k8s.io/gengo"
  branch = "master"

# to work around https://github.com/golang/dep/issues/1799
[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "https://github.com/fsnotify/fsnotify.git"

[[constraint]]
  name = "github.com/aporeto-inc/oxy"
  branch = "master"

[[constraint]]
  name = "go.aporeto.io/netlink-go"
  branch = "master"

[[constraint]]
  name = "github.com/hashicorp/go-version"
  version = "v1.0.0"

[prune]
  go-tests = true
  unused-packages = true

[[override]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.0"

