required = ["github.com/docker/distribution"]

[[constraint]]
  branch = "release-3.11.0"
  name = "github.com/aporeto-inc/go-ipset"

[[constraint]]
  name = "github.com/docker/docker"
  version = "v17.05.0-ce-rc3"

[[constraint]]
  name = "github.com/docker/distribution"
  revision = "b38e5838b7b2f2ad48e06ec4b500011976080621"

# Conntrack dependencies from forked branches
[[override]]
  name = "github.com/mdlayher/netlink"
  source = "https://github.com/aporeto-inc/netlink.git"
  revision = "7e948d4190d773b1315fb031a8ae83d8a302f7c9"
  
[[constraint]]
  name = "github.com/ti-mo/conntrack"
  source = "https://github.com/aporeto-inc/conntrack.git"
  revision = "309d2d6a30782ae8f0c68f2dda0774966523e469"
  
#
# The most significant dependency for the Kubernetes monitor: the controller-runtime
# NOTE: change with care and always adjust the Kubernetes dependencies below
#
[[override]]
  name = "sigs.k8s.io/controller-runtime"
  version = "v0.1.10"

#
# Kubernetes dependencies
# NOTE: always match exactly to what controller-runtime uses
#
[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.13.1"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.13.1"

[[constraint]]
  branch = "sirupsen"
  name = "github.com/aporeto-inc/oxy"

[[constraint]]
  branch = "release-3.11.0"
  name = "go.aporeto.io/netlink-go"

[[constraint]]
  name = "github.com/hashicorp/go-version"
  version = "v1.0.0"

[[override]]
  name = "sigs.k8s.io/controller-runtime"
  version = "v0.1.10"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.13.1"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.13.1"

[[override]]
  name = "k8s.io/apiserver"
  version = "kubernetes-1.13.1"

[[override]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.13.1"

[[override]]
  branch = "master"
  name = "k8s.io/gengo"

[prune]
  go-tests = true
  unused-packages = true
